
enum ExchangeSegment { NSE_EQ, NSE_FNO, NSE_CURRENCY,BSE_EQ,BSE_FNO,BSE_CURRENCY,MCX_COMM }
enum ProductType {CNC,INTRADAY,MARGIN,CO,BO,MTF}
enum OrderType {LIMIT,MARKET,STOP_LOSS,STOP_LOSS_MARKET}
enum Validity {DAY,IOC }
enum OrderStatus {TRANSIT, PENDING, REJECTED, CANCELLED, TRADED ,EXPIRED}
